sudo: false
language: go
go:
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls

script:
  - ./test.sh
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
