name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: src/github.com/target/go-arty

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            mkdir /home/runner/work/go-arty/bin
            export GOPATH=/home/runner/work/go-arty
            export PATH=$PATH:/home/runner/work/go-arty/bin
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        export GOPATH=/home/runner/work/go-arty
        go test -v -race ./...
        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
        # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
        go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)

